# Generated by Django 5.2.3 on 2025-06-11 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del alimento')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca (Opcional)')),
                ('portion_size_g', models.DecimalField(decimal_places=2, default=100.0, max_digits=7, verbose_name='Tamaño de porción (g)')),
                ('portion_unit', models.CharField(default='g', max_length=50, verbose_name='Unidad de porción')),
                ('calories', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Calorías (kcal)')),
                ('proteins', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Proteínas (g)')),
                ('fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Grasas (g)')),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Carbohidratos (g)')),
                ('sugars', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Azúcares (g)')),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Fibra (g)')),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Sodio (mg)')),
                ('is_custom', models.BooleanField(default=False, verbose_name='¿Es un alimento personalizado?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_food_items', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['name'],
            },
        ),
    ]
